include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    empty_catches: ignore
    no_logic_in_create_state: ignore
    prefer_const_constructors: ignore
    prefer_const_constructors_in_immutables: ignore
    sort_child_properties_last: ignore
    unnecessary_brace_in_string_interps: ignore
    use_build_context_synchronously: ignore
    use_key_in_widget_constructors: ignore
