name: magik_antivirus
description: "Trabajo de Fin de Grado de Erik Amo"
publish_to: 'none'
version: 0.0.3

environment:
  sdk: ^3.5.4

dependencies:
  country_flags: ^3.1.0
  properties: ^2.1.1
  mysql_client: ^0.0.27
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.3.4+4
  flutter_svg: ^2.0.16
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  logger: ^2.5.0
  crypto: ^3.0.1
  fluttertoast: ^8.2.10
  flutter_markdown: ^0.7.5
  file_picker: ^8.1.7
  device_info_plus: ^11.2.0
  flutter_background_service: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/icons/linux.svg
   - assets/icons/macos.svg
   - assets/icons/windows.svg
   - assets/changelogs/