name: magik_antivirus
description: "Trabajo de Fin de Grado de Erik Amo"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  country_flags: ^3.1.0
  properties: ^2.1.1
  mysql_client: ^0.0.27
  sqflite_common_ffi: ^2.3.4+4
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/Files/data.properties