name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    # Android APK (solo en Linux)
    - name: Build APK for Android
      if: matrix.os == 'ubuntu-latest'
      run: flutter build apk --release

    - name: Upload Android APK
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    # Linux
    - name: Build Linux app
      if: matrix.os == 'ubuntu-latest'
      run: flutter build linux --release

    - name: Upload Linux build
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: build/linux/arm64/release/bundle

    # Windows
    - name: Build Windows app
      if: matrix.os == 'windows-latest'
      run: flutter build windows --release

    - name: Upload Windows build
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: build/windows/x64/runner/Release
