name: Flutter Build & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [android, windows, macos]
        include:
          - target: android
            os: windows-latest
          - target: macos
            os: macos-latest
          - target: windows
            os: windows-latest
          #- target: linux
          #  os: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: stable
          
      - name: Install Linux dependencies
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libblkid-dev liblzma-dev libsecret-1-dev libjsoncpp-dev libsqlite3-dev libxkbcommon-dev ninja-build pkg-config

          
      - name: Enable Windows desktop support
        if: matrix.target == 'windows'
        run: |
          flutter config --enable-windows-desktop
          flutter create --platforms=windows .
      
      - name: Enable macOS desktop support
        if: matrix.target == 'macos'
        run: |
          flutter config --enable-macos-desktop
          flutter create --platforms=macos .

      - name: Enable Linux desktop support
        if: matrix.target == 'linux'
        run: |
          flutter config --enable-linux-desktop
          flutter create --platforms=linux .

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Android)
        if: matrix.target == 'android'
        run: flutter build apk --release

      - name: Build Windows
        if: matrix.target == 'windows'
        run: flutter build windows --release

      - name: Build macOS
        if: matrix.target == 'macos'
        run: flutter build macos --release

      - name: Build Linux
        if: matrix.target == 'linux'
        run: flutter build linux --release
        

      - name: Upload Android artifact
        if: matrix.target == 'android'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-android
          path: build/app/outputs/flutter-apk/*.apk
          
      - name: Upload Windows artifact
        if: matrix.target == 'windows'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-windows
          path: build/windows/runner/Release/
          
      - name: Upload macOS artifact
        if: matrix.target == 'macos'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-macos
          path: build/macos/Build/Products/Release/
          
      - name: Upload Linux artifact
        if: matrix.target == 'linux'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-linux
          path: build/linux/x64/release/bundle/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Extracted version: $version"

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip all builds
        run: |
          cd artifacts
          ls -la
          zip -r flutter_builds_${{ env.VERSION }}.zip .
          mv flutter_builds_${{ env.VERSION }}.zip ../

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          artifacts: flutter_builds_${{ env.VERSION }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true